# Generated by Django 5.2.6 on 2025-09-21 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecordOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('feed_consumed', models.FloatField(null=True)),
                ('feed_type', models.CharField(max_length=100, null=True)),
                ('water_consumed', models.FloatField(null=True)),
                ('total_eggs', models.IntegerField(null=True)),
                ('broken_eggs', models.IntegerField(null=True)),
                ('dirty_eggs', models.IntegerField(null=True)),
                ('good_eggs', models.IntegerField(null=True)),
                ('fan_working', models.BooleanField(default=True)),
                ('fan_hours', models.FloatField(blank=True, null=True)),
                ('light_working', models.BooleanField(default=True)),
                ('light_hours', models.FloatField(blank=True, null=True)),
                ('feeder_working', models.BooleanField(default=True)),
                ('feeder_hours', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('mortality', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
