# Generated by Django 5.2.6 on 2025-12-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecordsiaf',
            name='ai_birds_count',
        ),
    ]
