# Generated by Django 5.2.6 on 2025-09-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrecordoriginal',
            old_name='feeder_hours',
            new_name='ai_hours',
        ),
        migrations.RenameField(
            model_name='dailyrecordoriginal',
            old_name='broken_eggs',
            new_name='damaged_egg_evening',
        ),
        migrations.RenameField(
            model_name='dailyrecordoriginal',
            old_name='dirty_eggs',
            new_name='damaged_egg_morning',
        ),
        migrations.RenameField(
            model_name='dailyrecordoriginal',
            old_name='good_eggs',
            new_name='double_egg_evening',
        ),
        migrations.RenameField(
            model_name='dailyrecordoriginal',
            old_name='total_eggs',
            new_name='double_egg_morning',
        ),
        migrations.RenameField(
            model_name='dailyrecordoriginal',
            old_name='light_hours',
            new_name='fogger_hours',
        ),
        migrations.RenameField(
            model_name='dailyrecordoriginal',
            old_name='feed_consumed',
            new_name='water_intake',
        ),
        migrations.RemoveField(
            model_name='dailyrecordoriginal',
            name='fan_working',
        ),
        migrations.RemoveField(
            model_name='dailyrecordoriginal',
            name='feed_type',
        ),
        migrations.RemoveField(
            model_name='dailyrecordoriginal',
            name='feeder_working',
        ),
        migrations.RemoveField(
            model_name='dailyrecordoriginal',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='dailyrecordoriginal',
            name='light_working',
        ),
        migrations.RemoveField(
            model_name='dailyrecordoriginal',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='dailyrecordoriginal',
            name='water_consumed',
        ),
        migrations.AddField(
            model_name='dailyrecordoriginal',
            name='artificial_insemination',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='dailyrecordoriginal',
            name='fan_used',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='dailyrecordoriginal',
            name='feed_evening',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordoriginal',
            name='feed_morning',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordoriginal',
            name='fogger_used',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='dailyrecordoriginal',
            name='medicine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordoriginal',
            name='total_egg_evening',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordoriginal',
            name='total_egg_morning',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordoriginal',
            name='tray_egg_evening',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordoriginal',
            name='tray_egg_morning',
            field=models.IntegerField(null=True),
        ),
    ]
