# Generated by Django 5.2.6 on 2025-10-11 02:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_feeder_hours_dailyrecordoriginal_ai_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecordCross',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('feed_morning', models.IntegerField(null=True)),
                ('feed_evening', models.IntegerField(null=True)),
                ('water_intake', models.FloatField(null=True)),
                ('tray_egg_morning', models.IntegerField(null=True)),
                ('total_egg_morning', models.IntegerField(null=True)),
                ('damaged_egg_morning', models.IntegerField(null=True)),
                ('double_egg_morning', models.IntegerField(null=True)),
                ('tray_egg_evening', models.IntegerField(null=True)),
                ('total_egg_evening', models.IntegerField(null=True)),
                ('damaged_egg_evening', models.IntegerField(null=True)),
                ('double_egg_evening', models.IntegerField(null=True)),
                ('artificial_insemination', models.CharField(default='No', max_length=3)),
                ('ai_hours', models.FloatField(blank=True, null=True)),
                ('fogger_used', models.CharField(default='No', max_length=3)),
                ('fogger_hours', models.FloatField(blank=True, null=True)),
                ('fan_used', models.CharField(default='No', max_length=3)),
                ('fan_hours', models.FloatField(blank=True, null=True)),
                ('medicine', models.CharField(blank=True, max_length=255, null=True)),
                ('mortality', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
