# Generated by Django 5.2.6 on 2025-12-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_dailyrecordsiaf_ai_birds_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecordsiaf',
            name='ai_birds_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
