# Generated by Django 5.1.1 on 2025-10-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_dailyrecordcross'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_birds', models.IntegerField(default=0)),
                ('cross_birds', models.IntegerField(default=0)),
                ('batch_start_date', models.DateField()),
                ('batch_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
