# Generated by Django 5.1.1 on 2025-10-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_birdscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birdscount',
            name='batch_end_date',
        ),
        migrations.RemoveField(
            model_name='birdscount',
            name='batch_start_date',
        ),
        migrations.AddField(
            model_name='birdscount',
            name='cross_batch_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birdscount',
            name='original_batch_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
