# Generated by Django 5.1.1 on 2025-10-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_birdscount_batch_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdscount',
            name='cross_batch_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birdscount',
            name='original_batch_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
