# Generated by Django 5.2.6 on 2025-11-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_birdscount_cross_batch_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecordoriginal',
            name='light_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordoriginal',
            name='light_used',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
