# Generated by Django 5.2.6 on 2025-12-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_dailyrecordcross_light_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecordcross',
            name='feed_evening_bundles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordcross',
            name='feed_morning_bundles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordoriginal',
            name='feed_evening_bundles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordoriginal',
            name='feed_morning_bundles',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
