# Generated by Django 5.2.6 on 2025-12-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_dailyrecordcross_feed_evening_bundles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecordcross',
            name='mortality_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordoriginal',
            name='mortality_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
