# Generated by Django 5.1.1 on 2025-12-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_feedstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedstock',
            name='closing_stock_bundles',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='feedstock',
            name='closing_stock_kg',
            field=models.FloatField(default=0),
        ),
    ]
