# Generated by Django 5.2.6 on 2025-12-04 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_feedstock_closing_stock_bundles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaleBirdsStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('birds_count', models.IntegerField(default=0)),
                ('mortality_count', models.IntegerField(default=0)),
                ('mortality_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
    ]
