# Generated by Django 5.2.6 on 2025-12-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_malebirdsstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaleBirdsStock',
        ),
    ]
