# Generated by Django 5.2.6 on 2025-12-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_malebirdsstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedstock',
            name='closing_stock_bundles',
        ),
        migrations.RemoveField(
            model_name='feedstock',
            name='closing_stock_kg',
        ),
    ]
