# Generated by Django 5.2.6 on 2025-12-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_malebirdsmortality_malebirdsstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyRecordOriginal',
        ),
        migrations.RemoveField(
            model_name='birdscount',
            name='original_batch_end_date',
        ),
        migrations.RemoveField(
            model_name='birdscount',
            name='original_batch_start_date',
        ),
        migrations.RemoveField(
            model_name='birdscount',
            name='original_birds',
        ),
    ]
