# Generated by Django 5.2.6 on 2025-12-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_femalesbatchrecord_malebatchrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BatchRecord',
        ),
        migrations.DeleteModel(
            name='FemalesBatchRecord',
        ),
        migrations.DeleteModel(
            name='MaleBatchRecord',
        ),
    ]
