# Generated by Django 5.2.6 on 2025-12-05 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_delete_batchrecord_delete_femalesbatchrecord_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyRecordCross',
            new_name='DailyRecordSIAF',
        ),
        migrations.RenameField(
            model_name='birdscount',
            old_name='cross_batch_end_date',
            new_name='SIAF_batch_end_date',
        ),
        migrations.RenameField(
            model_name='birdscount',
            old_name='cross_batch_start_date',
            new_name='SIAF_batch_start_date',
        ),
        migrations.RenameField(
            model_name='birdscount',
            old_name='cross_birds',
            new_name='SIAF_birds',
        ),
    ]
