# Generated by Django 5.2.6 on 2025-12-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_malebirdsstock_batch_status'),
        ('myapp', '0023_birdscount_status'),
    ]

    operations = [
    ]
