# Generated by Django 5.2.6 on 2025-12-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_birdscount_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birdscount',
            options={'ordering': ['-SIAF_batch_start_date']},
        ),
        migrations.RemoveField(
            model_name='malebirdsmortality',
            name='notes',
        ),
    ]
