# Generated by Django 5.1.1 on 2025-12-06 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_femalebirdsmortality_femalebirdsstock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='femalebirdsmortality',
            name='stock_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.femalebirdsstock'),
        ),
        migrations.AddField(
            model_name='malebirdsmortality',
            name='stock_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.malebirdsstock'),
        ),
    ]
