# Generated by Django 5.2.6 on 2025-12-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_femalebirdsmortality_stock_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='femalebirdsmortality',
            name='stock_batch',
        ),
        migrations.RemoveField(
            model_name='malebirdsmortality',
            name='stock_batch',
        ),
    ]
