# Generated by Django 5.2.6 on 2025-12-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_femalebirdsmortality_stock_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecordsiaf',
            name='mortality',
        ),
        migrations.RemoveField(
            model_name='dailyrecordsiaf',
            name='mortality_reason',
        ),
    ]
