# Generated by Django 5.2.6 on 2025-12-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_dailyrecordsiaf_mortality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecordsiaf',
            name='temperature_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordsiaf',
            name='temperature_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordsiaf',
            name='temperature_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordsiaf',
            name='temperature_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordsiaf',
            name='temperature_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordsiaf',
            name='temperature_6',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
