# Generated by Django 5.2.6 on 2025-12-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_dailyrecordsiaf_temperature_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecordsiaf',
            name='total_egg_evening',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecordsiaf',
            name='total_egg_morning',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecordsiaf',
            name='tray_egg_evening',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecordsiaf',
            name='tray_egg_morning',
            field=models.FloatField(null=True),
        ),
    ]
