# Generated by Django 5.2.6 on 2025-12-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_malefeedstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaleFeedStock',
        ),
    ]
