# Generated by Django 5.2.6 on 2025-12-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_femalefeedintake_malefeedintake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FemaleFeedIntake',
        ),
        migrations.DeleteModel(
            name='MaleFeedIntake',
        ),
    ]
