# Generated by Django 5.1.1 on 2025-12-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_delete_femalefeedintake_delete_malefeedintake'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecordsiaf',
            name='feed_female_evening',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordsiaf',
            name='feed_female_evening_bundles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordsiaf',
            name='feed_female_morning',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordsiaf',
            name='feed_female_morning_bundles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordsiaf',
            name='feed_male_evening',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordsiaf',
            name='feed_male_evening_bundles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordsiaf',
            name='feed_male_morning',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecordsiaf',
            name='feed_male_morning_bundles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecordsiaf',
            name='feed_evening',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecordsiaf',
            name='feed_morning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecordsiaf',
            name='water_intake',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
